on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout projects
      uses: actions/checkout@main
     
    - name: create tag 
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag v1.0.1
        git push origin v1.0.1

    - name: Rebase pull requests
      if: success()
      uses: linhbn123/rebase-pull-requests@v1.0.1

#       - uses: avakar/tag-and-release@v1
#         with:
#           tag_name: v123
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
