on: workflow_dispatch

name: Run Tests

jobs:
  build:
    name: Run test and Create coverage report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install yarn dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run tests and create a report file
        run: yarn test

      - name: Read the report file and send data to google sheet
        run: node ./analysisCoverage.js
