on: workflow_dispatch

name: Run Tests

jobs:
  build:
    name: Run test and Create coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run tests
        run: yarn test
